pipeline {
    agent any

    environment {
        // Example: set Python version if you use pyenv/venv
        VENV_DIR = ".venv"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/MarwanIssa100/alx-backend-python.git',
                credentialsId: 'github-credentials'
            }
        }

        stage('Set up Python environment') {
            steps {
                sh '''
                    python3 -m venv $VENV_DIR
                    source $VENV_DIR/bin/activate
                    pip3 install --upgrade pip
                    pip3 install  messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    source $VENV_DIR/bin/activate
                    pytest --junitxml=reports/pytest-report.xml
                '''
            }
        }

        stage('Publish Report') {
            steps {
                junit 'reports/pytest-report.xml'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t $DOCKER_IMAGE:$DOCKER_TAG ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', 
                                                usernameVariable: 'DOCKER_USER', 
                                                passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $DOCKER_IMAGE:$DOCKER_TAG
                    '''
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'reports/**/*.xml', fingerprint: true
        }
        failure {
            mail to: 'team@example.com',
                subject: "Build Failed in Jenkins: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: "Check Jenkins for details: ${env.BUILD_URL}"
        }
    }
}
